/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alura.conversorchallengeone;

import divisas.Conver;
import divisas.Conversiones;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author samll
 */
public class DivisasC extends javax.swing.JFrame {
    
    ArrayList<String> sC;
    
    Conver convt;
    
    public DivisasC() {
        
        initComponents();
        
        this.convt = new Conver();
        
        this.sC = new ArrayList<>();
        
        generarDatos();
        loadSelectC();
    }
    
    private void generarDatos() {
        this.sC.add("Dolar");
        this.sC.add("Euro");
        this.sC.add("Libra Esterlina");
        this.sC.add("Yen Japonés");
        this.sC.add("Won Sur-Coreano");
    }
    
    private void loadSelectC() {
        this.selectD.removeAllItems();
        this.selectC.removeAllItems();
        for (String div : sC) {
            this.selectD.addItem(div);
            this.selectC.addItem(div);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        selectD = new javax.swing.JComboBox<>();
        selectC = new javax.swing.JComboBox<>();
        inputD = new javax.swing.JFormattedTextField();
        btnC = new javax.swing.JButton();
        lblD = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblRequired = new javax.swing.JLabel();
        lblDL = new javax.swing.JLabel();
        lblCL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Hack Nerd Font", 1, 24)); // NOI18N
        jLabel1.setText("CONVERSOR DE DIVISAS");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Hack Nerd Font", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VOLVER");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        selectD.setFont(new java.awt.Font("Hack Nerd Font", 0, 14)); // NOI18N
        selectD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectC.setFont(new java.awt.Font("Hack Nerd Font", 0, 14)); // NOI18N
        selectC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inputD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        inputD.setFont(new java.awt.Font("Hack Nerd Font", 0, 14)); // NOI18N

        btnC.setFont(new java.awt.Font("Hack Nerd Font", 1, 18)); // NOI18N
        btnC.setText("CONVERTIR");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        lblD.setFont(new java.awt.Font("Hack Nerd Font", 1, 18)); // NOI18N
        lblD.setText("0.00");

        jLabel4.setFont(new java.awt.Font("Hack Nerd Font", 1, 36)); // NOI18N
        jLabel4.setText("=");

        lblC.setFont(new java.awt.Font("Hack Nerd Font", 1, 18)); // NOI18N
        lblC.setText("0.00");

        lblRequired.setFont(new java.awt.Font("Hack Nerd Font", 2, 14)); // NOI18N
        lblRequired.setForeground(new java.awt.Color(255, 51, 51));
        lblRequired.setText(" ");

        lblDL.setFont(new java.awt.Font("Hack Nerd Font", 2, 12)); // NOI18N
        lblDL.setForeground(new java.awt.Color(153, 153, 153));
        lblDL.setText(" ");

        lblCL.setFont(new java.awt.Font("Hack Nerd Font", 2, 12)); // NOI18N
        lblCL.setForeground(new java.awt.Color(153, 153, 153));
        lblCL.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblD)
                            .addComponent(jLabel4)
                            .addComponent(lblC)
                            .addComponent(lblDL)
                            .addComponent(lblCL))))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(selectD, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectC, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblRequired))
                            .addComponent(inputD, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(inputD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRequired)
                .addGap(18, 18, 18)
                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
        new ConversorMain().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        if (this.inputD.getValue() != null) {
            this.lblRequired.setText(" ");
            double convD = Double.parseDouble(this.inputD.getValue().toString());
            
            String coD = this.selectD.getSelectedItem().toString();
            String coA = this.selectC.getSelectedItem().toString();
            
            double cvc = convt.convertir(new Conversiones(coD, coA), convD);
            
            DecimalFormat cvcF = new DecimalFormat("#,###.0000");
            
            this.lblD.setText(String.valueOf(cvcF.format(convD)));
            this.lblDL.setText(coD);
            this.lblC.setText(String.valueOf(cvcF.format(cvc)));
            this.lblCL.setText(coA);
        } else {
            this.lblRequired.setText("Campo Requerido!!!");
        }
        
        this.inputD.setValue(null);
    }//GEN-LAST:event_btnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DivisasC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DivisasC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DivisasC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DivisasC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DivisasC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JFormattedTextField inputD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCL;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblDL;
    private javax.swing.JLabel lblRequired;
    private javax.swing.JComboBox<String> selectC;
    private javax.swing.JComboBox<String> selectD;
    // End of variables declaration//GEN-END:variables
}
